### ISSUE TITLE
按任意键会关闭弹出窗口

### ISSUE THREAD

**Issue by MisLink** [magic-FE/translate-man#11]
这导致无法使用快捷键复制翻译结果。

**Comment by chen844033231** [comment]
@MisLink 采用鼠标右键复制 目前在默认按 ctrl 键是不会关闭弹窗的 你如果是 mac 可以设置为 command 键

**Comment by MisLink** [comment]
![default](https://cloud.githubusercontent.com/assets/8280169/26522514/3d3c818a-4335-11e7-92a8-db4d4e192a2d.png)
这个窗口中按任意键都会使窗口关闭，虽然可以选中文本右键复制，但是怎么都觉得有点奇怪。。查词的时候手还在ctrl上，选中按C比较自然吧。
