### ISSUE TITLE
Firefox version of this extension?

### ISSUE THREAD

**Issue by kutsan** [magic-FE/translate-man#12]
It would be so much great if you could make a Firefox port.

**Comment by cloudIC** [comment]
it can be used in firefox

**Comment by kutsan** [comment]
How?

**Comment by babyfiv5** [comment]
我也同样希望能在火狐上用这个插件。这个插件和谷歌翻译插件一样，可以直接复制pdf文档中的字符忽略换行符，但是谷歌翻译插件只在.com域名下查询，国内要翻墙才能用，所以这个插件是我现在经常使用的。由于我在linux下经常使用火狐，在火狐上好像没有类似的插件，这个插件如果能够转到火狐上应该很不错的，是否可以考虑在readme加一段解释如何在火狐上使用 这个插件？

**Comment by cloudIC** [comment]
@babyfiv5 嗯 了解你的需求了

**Comment by cloudIC** [comment]
Have been submitted to the Firefox plugin waiting for review.

**Comment by cloudIC** [comment]
firefox link: https://addons.mozilla.org/zh-CN/firefox/addon/%E7%BF%BB%E8%AF%91%E4%BE%A0-translate-man/
