### ISSUE TITLE
兩行以上劃詞無法顯示翻譯?

### ISSUE THREAD

**Issue by hdd60311** [magic-FE/translate-man#15]
例如像這樣點擊圖標就無法顯示翻譯框了
![translate-man](https://user-images.githubusercontent.com/5089290/34381588-6890648e-eb44-11e7-8d80-fe299de87dc2.png)

**Comment by cloudIC** [comment]
采用的谷歌翻译接口 那边翻译不了 我这边也没办法 可以一行一行翻译下
