### ISSUE TITLE
按下组合键（如Ctrl+C）不翻译

### ISSUE THREAD

**Issue by OliverLew** [magic-FE/translate-man#18]
Ctrl确实很方便，但是Ctrl也用在很多其他组合键中（其他按键Shift/Win/Alt单独按都有其他作用），有些时候选取了文字想复制，结果还是弹出了翻译，可能体验不太好。能不能在只按了快捷键时弹出翻译？

更新：我又试了一下，在Ctrl和C间隔很慢时，才会弹出翻译，就是说你检测的是按键按下的事件。能否考虑换成检测按键抬起后再翻译呢？

**Comment by cloudIC** [comment]
确实可以优化成按键抬起 下个版本增加下

**Comment by cloudIC** [comment]
done at next release version v2.5.3
