### ISSUE TITLE
能去除原文显示吗？

### ISSUE THREAD

**Issue by Juli1546** [magic-FE/translate-man#19]
现在的原文显示太占地方了，阻挡了中文阅读

**Comment by cloudIC** [comment]
是因为翻译了一大堆文字吗 后期考虑下做个配置 看还有人有没有这样的需求的  先 pending 在这里

**Comment by zjbdiy** [comment]
我也需要这个功能  还有   我取消划词自动翻译之后   怎么触发翻译呀  抱歉 我没找到方法

**Comment by cloudIC** [comment]
双击翻译 或者选中后按ctrl

**Comment by zjbdiy** [comment]
双击只能翻译单词  而我希望翻译句子  选中后按ctrl无效果   win10 firefox 58.0.2 X64

**Comment by cloudIC** [comment]
你选个单词 然后按ctrl看有效没 如果有效 那翻译句子就是有效的 除非句子翻译不出来

**Comment by zjbdiy** [comment]
谢谢你的回复  我没有开启ctrl选项,怪不得没有反映   我浏览网页有个不好的习惯就是喜欢选中文字,不能自动翻译   很感谢你的奉献
