### ISSUE TITLE
[New Hotkey] A Hotkey for a manual typing

### ISSUE THREAD

**Issue by BoQsc** [magic-FE/translate-man#20]
![IntroGIF](https://i.cubeupload.com/KjpbDK.gif)

## Introduction to a New Feature
The Hotkey default combination, for opening Translate Man: **CTRL + Q** 
- Which would open Translate Man translator 
- and you could type in the word for translation.

## Why in need of such Feature?
This is the most useful while listening to a video or an audio.
As this Hotkey will allow you to quickly access translator, and type in a word for clarified translation. (That you didn't understood while listening to an audio or a video)

This is one of the crucial features, that keeps me stay with a Chrome browser.

## Additional functionality for this Feature
If the text is selected and **CTRL + Q**  is pressed:

- Translate Man would open up
- And pastes the selected content into the Translate Man

**Comment by cloudIC** [comment]
This is a good idea, adopt this opinion.

**Comment by cloudIC** [comment]
done use `ctrl + q`
