### ISSUE TITLE
[Remove or Hide] The logo Inside Translate Man

### ISSUE THREAD

**Issue by BoQsc** [magic-FE/translate-man#21]
## Logo takes very large space inside the extension.
![re](http://i.cubeupload.com/jNZHm8.png)
Translate Man already has a logotype outside the extension that points to the extension's window.
There is no need for another logotype especially this huge as shown above.

Possible solutions:
- **remove the logotype inside extension's window**, because there is already a logotype pointing to the extension's window.
- **hide logotype inside extension's window** (as soon as hitting the Enter key, 
or starting the translation to the other language).

## A huge logotype that takes ~30% of space, might have huge impact while reading the webpage or watching a video. 
![Removal of the logo](http://i.cubeupload.com/30Wutf.png)

**Comment by cloudIC** [comment]
sorry i think has logo is ok
