### ISSUE TITLE
[Enhancement] Begin a translation after writing a single character.

### ISSUE THREAD

**Issue by BoQsc** [magic-FE/translate-man#22]
## Unnecessity Pressing Enter every time you write a word

The tiredness of pressing Enter every time you finished writing a word, might accumulate while spending longer time translating.

One of the best improvement would be to **just begin translation after a single character is typed into the Translate Man's translation field called "Enter Text"**

![tesres](http://i.cubeupload.com/hjCyR1.gif)

**Comment by cloudIC** [comment]
I think it is not necessary
