### ISSUE TITLE
ctrl+单击时不翻译，通常用来打开后台标签页

### ISSUE THREAD

**Issue by OliverLew** [magic-FE/translate-man#26]
又是一个组合键的体验问题，不过这个组合可能没有很多人用，也不知道是否容易实现。

**Comment by cloudIC** [comment]
目前可以自定义一个按钮 个人觉得不用多个按键组合 本来就是个轻量级的工具 有选择文字的情况下 按一个按键即可

**Comment by OliverLew** [comment]
我表述的可能不清楚。

我的意思是，基本在所有浏览器中，Ctrl+单击链接是用来在另一个标签页打开链接的，但是目前会弹出翻译窗口，我理想的状态是不要弹出翻译。**所以能否区分"Ctrl+单击"和单独的"Ctrl"**。

当然如果不容易实现的话，使用现有的自定义其他按钮的方式也完全没有问题。

**Comment by cloudIC** [comment]
可以做下区分
