### ISSUE TITLE
翻译侠 V3.0 重构计划及功能征集

### ISSUE THREAD

**Issue by cloudIC** [magic-FE/translate-man#27]
# 缘由
作者本人英文水平有限，平时对浏览器需求比较大，而在谷歌商店又没找到比较好的翻译插件（有的功能好，UI不友好，UI好，功能缺失）。所以打算自己做个平时自己用的，前期个人需求还是主要是单词为主，没做整页翻译，而且用的 react 框架写的，体积还是有点大，并且有时翻译不出来，所以计划重构下，并添加后端功能。

# 架构
前端：轻量级 Vue
后端：高并发 gin（go语法）
数据库：ES

# 功能列表
原有功能基础上增加：
- [ ] 整页翻译
- [ ] 即输即译
- [ ] PDF支持
- [ ] 单词本

**Comment by HaoChuan9421** [comment]
看到你的计划就已经很期待了！但是整页翻译感觉意义不大吧？Chrome自带就有整页翻译，单词本希望可以支持QQ或者微信等第三方账号登陆，方便同步，也省去注册账号的麻烦。加油！！！

**Comment by charles9056** [comment]
加油，支持！翻译侠太棒了！
另建议：整页翻译 设置一个选项下拉菜单选择 各种翻译api，比如谷歌，百度，搜狗，微软等等。
然后点击“翻译侠”图标即可快速进行整页翻译。

**Comment by cloudIC** [comment]
done
