### ISSUE TITLE
设置第二语言为英文

### ISSUE THREAD

**Issue by ItsFated** [magic-FE/translate-man#3]
如果把原文和译文都选择为自动检测，则应该是选中中文则翻译成英文，选中英文则翻译成中文，选中任意其他语言均翻译成中文。

**Comment by likun7981** [comment]
现在的功能就是这样的，只是翻译不出来的，他就会返回原本的不会翻译

**Comment by chen844033231** [comment]
如果你把 原文 设置成自动检测, 则需要把你的原文发送到谷歌,才能确定你的 原文 语种.
如果你把 译文 设置为自动检测, 则是根据你的谷歌浏览器客户端语言设置的.
这款插件功能不仅仅局限于翻译中英文,所有不设置目标语种.
