### ISSUE TITLE
Translate mode without using keyboard

### ISSUE THREAD

**Issue by helperman** [magic-FE/translate-man#30]
I suggest you develop translate mode without using keyboard.
Here is my pseudo-code:

```
if (mouse hover over word AND mouse doesn't move 2 seconds)
  show popup translate

if (mouse moved)
  hide popup
```

It would be million times easier than pressing Ctrl button.
Many users dream of it.
Really.

**Comment by helperman** [comment]
I'm happy to hear it!

**Comment by cloudIC** [comment]
done in v3, thanks for your advice.
