### ISSUE TITLE
V3.0 会在网址后加 #/ 符号

### ISSUE THREAD

**Issue by jingyu9575** [magic-FE/translate-man#32]
安装扩展V3.0后，打开任意网址，后面会自动加上 #/ 符号。火狐和Chrome都有这个问题。
这似乎和 vue-router 有关。如果切换到 [history mode](https://router.vuejs.org/en/essentials/history-mode.html)，就不会改变网址，但按钮的弹出页面会出错。

~~目前我是这样解决的：~~ Edit: 这个方法与使用history.pushState的网站（如GitHub）冲突。
<s>
```js
export default new VueRouter({
  mode: location.protocol === 'moz-extension:' ? undefined : 'history',
  routes: [
    ...
  ],
})
```
</s>

![default](https://user-images.githubusercontent.com/8923139/37659040-402c97da-2c92-11e8-92ec-beb2141556fa.png)
![default](https://user-images.githubusercontent.com/8923139/37659060-4899893c-2c92-11e8-8b93-9b648739c6c3.png)

**Comment by cloudIC** [comment]
Already fixed in version 3.0.3, thanks.
