### ISSUE TITLE
所有标签链接栏里的链接 末尾出现#号

### ISSUE THREAD

**Issue by Crystal-RainSlide** [magic-FE/translate-man#33]
使用后所有标签链接栏里的链接末尾出现#号，具体为 https://moztw.org/dl/ 变成 https://moztw.org/dl/#/
另，拓展源码里有 .DS_Store 文件
最后，建议允许更改配色

**Comment by cloudIC** [comment]
see #32

**Comment by Crystal-RainSlide** [comment]
对夜间模式不友好~
