### ISSUE TITLE
昨天更新的版本显示有点bug

### ISSUE THREAD

**Issue by liuyanchen1994** [magic-FE/translate-man#34]
![image](https://user-images.githubusercontent.com/19524048/37698827-9353c932-2d1f-11e8-9f05-a847ebe0e175.png)

**Comment by cloudIC** [comment]
@liuyanchen1994 网址能贴下吗

**Comment by liuyanchen1994** [comment]
这个地址其他的网址是正常 https://www.newtonsoft.com/json/help/html/Introduction.htm

**Comment by cloudIC** [comment]
fixed in v3.0.4, thanks.
