### ISSUE TITLE
功能建议-建议增加跳转google翻译页面功能

### ISSUE THREAD

**Issue by Heier2013** [magic-FE/translate-man#35]
- 非常好用的一个翻译插件，简约轻便，感谢作者的付出。
- 建议增加类似Chrome下[Google 翻译](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb)拓展的小功能，点击“更多“后会跳转到谷歌翻译页面，方便查看更多可能的释义。
![_ _20180325215756](https://user-images.githubusercontent.com/9792980/37875946-78860910-3078-11e8-92ec-7bccca14e44b.png)
![_ _20180325215815](https://user-images.githubusercontent.com/9792980/37875947-78b8f56e-3078-11e8-8c6f-a590ef9e492a.png)

**Comment by cloudIC** [comment]
已经增加部分详细单词展示 v3.0.5
