### ISSUE TITLE
Tooltip disappearing

### ISSUE THREAD

**Issue by helperman** [magic-FE/translate-man#37]
Tooltip disappears on every miserable mouse movement upon the same word.
User's eyes are tired more intensively because of additional blinking.
It also interfere reading the translation.

See what I mean on these videos:
https://www.youtube.com/watch?v=7o8gwOz9LDY

How it could be implemented:
https://www.youtube.com/watch?v=k4pHJ6v8vEc

Test page:
http://www.iata.org/Pages/default.aspx

**Comment by cloudIC** [comment]
fixed in v3.0.7

**Comment by helperman** [comment]
Where I can find 3.0.7 ?
Only 3.0.8 available:
http://storage2.static.itmages.ru/i/18/0402/h_1522694250_6071001_d2c91c5666.png
And it doesn't look like it fixed.

**Comment by cloudIC** [comment]
Not your solution, tooltip will disappeared after 200ms.
