### ISSUE TITLE
Language detection

### ISSUE THREAD

**Issue by helperman** [magic-FE/translate-man#39]
Source language doesn't detected correctly sometimes.
For ex:

1. I set up "Russian" language in addon's options (I need English to Russian):
http://storage7.static.itmages.ru/i/18/0401/h_1522591239_7301394_43e18090b6.png

2. Open this web-page and hover mouse pointer to word "portal"
https://www.iata.org/publications/Pages/travel-documentation.aspx

Result:
A tooltip with translation Russian -> English is shown (instead English -> Russian).
http://storage9.static.itmages.ru/i/18/0401/h_1522591694_4379975_c42d431c98.png

**Comment by cloudIC** [comment]
Because the automatically detected language is russian. So will automatically translate russian into English.
For convenience, there is such a problem. At this point you can translate it manually.
