### ISSUE TITLE
无法翻译URL以 .html 结尾的界面

### ISSUE THREAD

**Issue by ItsFated** [magic-FE/translate-man#4]
http://docs.aws.amazon.com/zh_cn/mobile/sdkforandroid/developerguide/getting-started-lambda.html
这样以 .html 结尾的界面是无法翻译的
https://aws.amazon.com/cognito/pricing/
这样没有 .html 的界面就可以翻译
用的是QQ浏览器。。。

**Comment by likun7981** [comment]
@chen844033231

**Comment by chen844033231** [comment]
@ItsFated 测试可以 应该是网络请求比较慢  没有得到结果 可以重新试下
