### ISSUE TITLE
[Bug] 有些网站应用无法取词和选择翻译

### ISSUE THREAD

**Issue by XuJinNet** [magic-FE/translate-man#40]
@magic-FE 你好，谢谢你带来这么好的作品，这确实是一个很好的浏览器翻译插件，给我们阅读英文网页带来了帮助。
我在使用过程中发现有些网站应用无法取词和选择翻译，例如 https://feedly.com/i/latest，希望能够改进！

使用环境：
Firefox 59.0.2
OS：macOS 10.13.4

**Comment by cloudIC** [comment]
fixed in v3.0.7.

thank you for your feedback.

**Comment by XuJinNet** [comment]
你好，今天升级了 3.0.8 版本，但仍然不能翻译（ https://feedly.com/i/latest）

![1](https://user-images.githubusercontent.com/442382/38229483-8abf3e7a-373b-11e8-8a94-a2d5abac2915.png)
![2](https://user-images.githubusercontent.com/442382/38229487-919f08d8-373b-11e8-9174-e22ae25ac9b8.png)

**Comment by cloudIC** [comment]
fixed in v3.0.9 again.

**Comment by hdd60311** [comment]
@cloudIC 
測試了下在[這討論串](https://github.com/CanisLupus/swift-selection-search/issues/56)裡提到的網站或特定範圍裡都無法彈出翻譯

**Comment by XuJinNet** [comment]
Tested on feedly.com, is OK 👍
