### ISSUE TITLE
翻譯多段或多行文字時翻譯文字的顯示問題

### ISSUE THREAD

**Issue by hdd60311** [magic-FE/translate-man#42]
對照擴展[Simple Translate](https://addons.mozilla.org/zh-TW/firefox/addon/simple-translate/)
翻譯俠
![1](https://user-images.githubusercontent.com/5089290/38264400-6f8ffca6-37a5-11e8-8da4-54a888e769bd.png)

Simple Translate
![2](https://user-images.githubusercontent.com/5089290/38264401-6fca11ac-37a5-11e8-97b1-b15a5eedd431.png)

希望能採用像Simple Translate的顯示方式感覺比較方便閱讀

**Comment by cloudIC** [comment]
this is a good idea, has done in v3.0.10.
