### ISSUE TITLE
为何双击全选的段落无法翻译？

### ISSUE THREAD

**Issue by tangqiu0205** [magic-FE/translate-man#44]
如图所示
![41](https://user-images.githubusercontent.com/37826977/38716656-7e0a3c3a-3f14-11e8-81a8-c837294a4b35.png)

**Comment by cloudIC** [comment]
你应该是3击吧

**Comment by zhanghu0218** [comment]
好像还真是3击，有办法让它翻译吗？3击比拖拽要来的快。谢谢

**Comment by cloudIC** [comment]
后面考虑加上好了

**Comment by RemRemRemRe** [comment]
请问为啥翻译时没有音标? 商店页面的图片里是有音标的 我没找到设置选项
