### ISSUE TITLE
关于音标显示和美音英音的问题

### ISSUE THREAD

**Issue by Zhang21** [magic-FE/translate-man#46]
**背景**

由于本人看到不熟悉但常用的单词，会习惯性的看音标来纠正自己的发言。
但是，此插件对音标的内容显示很少，况且由于我习惯性使用英音，美音有一些发音异同。导致我查看单词发音的时候，感觉自己很多都不对，搞得自己都不知道该怎么读这些单词了。

<br>

**需求**
在菜单栏增加一个选择英音or美音的功能

**Comment by Zhang21** [comment]
还有一个问题，音标好像也匹配。

![image](https://user-images.githubusercontent.com/18358275/41397842-096c8c52-6fe8-11e8-8213-150358d93ebb.png)

**Comment by cloudIC** [comment]
这款插件用的谷歌翻译的 API ，没提供英语发音音标 所以做不了

**Comment by Zhang21** [comment]
@cloudIC 还有一个问题，这个谷歌翻译提供的音标我不会读呀，和英语书上有点差距。我在chrome商店也看到了有人说了这个问题。
搞得我都不知道怎么读这些单词了。

**Comment by Zhang21** [comment]
可以看我上面提供的那张图片。

**Comment by cloudIC** [comment]
美语的音标 这个做不了 抱歉
