### ISSUE TITLE
近期GOOGLE翻译更新，插件好像已失效

### ISSUE THREAD

**Issue by lzqwebsoft** [magic-FE/translate-man#59]
你好，近期发现translate google好像有更新，插件好像翻译出问题了，不响应结果，划词什么的功能都不顶用了。

以上，感谢作者开发的这么好用的插件！

**Comment by Zhang21** [comment]
google API 好像更新了，需要开发者修改一下。

**Comment by xyn8935** [comment]
呜呜呜，之前还觉得这翻译插件给了我希望呜呜，突然就不能用了，希望开发者能拯救一波

**Comment by lzqwebsoft** [comment]
更换了Chrome插件：[https://github.com/Selection-Translator/crx-selection-translate](https://github.com/Selection-Translator/crx-selection-translate)
![tim 20181204113101](https://user-images.githubusercontent.com/1137657/49417402-8445a500-f7b8-11e8-9e84-d8b9c16e0903.png)

**Comment by cloudIC** [comment]
done
