### ISSUE TITLE
可不可以在设置中添加一个不翻译选中中文的选项么

### ISSUE THREAD

**Issue by MarnoDev** [magic-FE/translate-man#6]
现在选中中文也会出现翻译框，但是并没有翻译成英文。然而根本上是不需要翻译中文，现在怎么关闭呢？

**Comment by chen844033231** [comment]
如果翻译的语种和你的主语种一样,不显示翻译文本,这个可以采纳.

- [ ] 将会在下个版本中加入这个功能

谢谢反馈

**Comment by likun7981** [comment]
@chen844033231  我觉得应该是

主语言和翻译语种一致，默认翻译为: ...

**Comment by chen844033231** [comment]
released v2.4.4
