### ISSUE TITLE
插件无效，要更新了

### ISSUE THREAD

**Issue by zhouhuajdsh** [magic-FE/translate-man#60]
插件无效，要更新了

**Comment by xyn8935** [comment]
好难过啊呜呜，插件用不了了，这么准的翻译插件！程序员用的很好！

**Comment by mazhewei** [comment]
我是火狐党，目前凑合用ImTranslator，期待更新

**Comment by weisd** [comment]
期待更新

**Comment by JIAN-JUN** [comment]
啊啊啊！！！今天突然发现没用了！求更新啊

**Comment by ouxu** [comment]
估计作者不在 我提 pr 了, 要不要先将就用下我编译的, https://tmp-i8c2ic0fm.now.sh/

**Comment by weisd** [comment]
> chrome://extensions 右上角切换为开发者模式试试

可以了，多谢

**Comment by weisd** [comment]
> chrome://extensions 右上角切换为开发者模式试试

这个有没有对应的alfred插件

**Comment by zhouhuajdsh** [comment]
> 
> 
> 估计作者不在 我提 pr 了, 要不要先将就用下我编译的, https://tmp-i8c2ic0fm.now.sh/

完美，火狐的版本也能顺便改下吗？

**Comment by ouxu** [comment]
> > 估计作者不在 我提 pr 了, 要不要先将就用下我编译的, https://tmp-i8c2ic0fm.now.sh/
> 
> 完美，火狐的版本也能顺便改下吗？

按照教程安装吧：[《Temporary Installation in Firefox》](https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox)

编译文件打包下载链接：[点我下载](https://translate-man-gj81me4td.now.sh/)

下载解压后按上面的教程加载，我测试发现画词翻译不能用

**Comment by Zhang21** [comment]
@ouxu 感谢。

环境： `win10 + chrome`

如果遇到安装后无法启用，请参考知乎答案——将此包改名.zip，之后解压，然后加载解压之后的文件夹就可以使用了。

<br>

> ps: 看到chrome商店上说不在维护，不知真假。希望各位把这个软件传承下去。

**Comment by scutxd** [comment]
非常感谢，这个插件非常已好用，正准备要把代码看看怎么修改的，结果你已经做好了。

**Comment by kairyou** [comment]
感谢 @ouxu 
作者如果不再维护, 有没有考虑转让给其他人? Chrome商店不更新实在可惜.

**Comment by liuyanchen1994** [comment]
@ouxu 感谢

**Comment by JIAN-JUN** [comment]
哇  ！！！感谢 @ouxu <https://github.com/ouxu>

Damon <notifications@github.com> 于2018年12月28日周五 下午5:09写道：

**Comment by cloudIC** [comment]
实在抱歉 以前由于一些原因为更新 近期会更新
