### ISSUE TITLE
hallo,chrome和firefox的插件都要更新啦！

### ISSUE THREAD

**Issue by zhang8223637** [magic-FE/translate-man#61]
hallo,chrome和firefox的插件都要更新啦！火狐的页面已经失效了

崔更的同时还是要感谢开发者提供了好用的工具~

**Comment by ouxu** [comment]
估计作者不在 我提 pr 了, 要不要先将就用下我编译的, https://tmp-i8c2ic0fm.now.sh/

**Comment by hel2o** [comment]
@ouxu 火狐用不了呢，在你的链接里下的

**Comment by hed1988** [comment]
> > @ouxu Chrome商店有人说作者停止维护了，您要不考虑下继续维护？
> 
> 我总不能把作者写的代码直接发布吧- - 要征求作者意见的

亲测你发布的插件有用，谢谢。希望你联系下作者，继续维护下去这么好用的工具。

**Comment by liuyanchen1994** [comment]
MIT协议可以随便发布

**Comment by cloudIC** [comment]
done

**Comment by zhang8223637** [comment]
> 
> 
> done

为表达感谢，只有打钱了！
