### ISSUE TITLE
[Bug] 在Firefox中启用本插件会导致某些富文本编辑器保存后出现额外<img>标签

### ISSUE THREAD

**Issue by SwimmingTiger** [magic-FE/translate-man#64]
具体来说，保存后帖子末尾会多出两个 `<img src="moz-extension://8eb198c9-7209-462c-ae8c-fa1a8f0d3aea/static/sound.svg">`标签，导致呈现出很不好的效果。某些网站还会拒绝内容的保存。如果无法切换到纯文本编辑器，则在禁用本插件之前永远无法在这些网站保存内容。

已知受影响网站：
* 3DM论坛
* NexusMod
* 微软开发者社区（拒绝保存内容）

以下动态图展示了3DM论坛受该Bug影响的情况，没有对帖子进行任何编辑，直接保存后就出现了两个额外的图片标签。

![翻译侠奇怪图片](https://user-images.githubusercontent.com/4986069/56094866-bce55000-5f09-11e9-9461-8352585c185e.gif)

禁用该插件后就不会出现这个情况。

**Comment by cloudIC** [comment]
Thank you for your feedback, it will be fixed in the next version.
