### ISSUE TITLE
翻译出来的结果和Google自身的不同

### ISSUE THREAD

**Issue by MafuyuC** [magic-FE/translate-man#75]
最近在用来整句翻译时发现翻译出来的结果，非常不流畅且有很多错误，和Google页面的翻译差距太大，是接口的问题吗
例如这两段：
1.China has planted billions of trees over the past four decades as part of its fight against expanding deserts, mostly in its north. Each year, the country sows seedlings over an area nearly the size of Ireland. It is even sharing its desert-control methods with others as part of its massive Belt and Road trade initiative.
2.And the afforestation drive is continuing apace: in 2018, the State Forestry Administration announced a target of 30% forest coverage by 2050. At the moment, the coverage is around 22%.
翻译侠的结果是：
1.中国已经种植了数十亿美元的树木，在过去四个十年其对沙漠扩大，主要是在北斗争的一部分。每年，全国母猪在区域爱尔兰近大小苗。它甚至和他人的分享其沙漠的控制方法及其强大的皮带和路贸易倡议的一部分。
2.和植树造林运动，继续快速：在2018年，国家林业局宣布，30％的森林覆盖率的目标，到2050年目前，覆盖率为22％左右。

**Comment by cloudfroster** [comment]
谷歌翻译接口是调用的：https://translate.google.cn
看下 README.md 中写的

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/65739051-96614d00-e116-11e9-9d9a-f00efaa8325a.png)

![image](https://user-images.githubusercontent.com/12741016/65739097-ba249300-e116-11e9-9911-70e7d8e6bb82.png)



![image](https://user-images.githubusercontent.com/12741016/65739077-ab3de080-e116-11e9-9f5a-f239292b9236.png)


![image](https://user-images.githubusercontent.com/12741016/65739126-d0caea00-e116-11e9-9389-76fa89f356c3.png)

**Comment by whtiehack** [comment]
的确有不准的问题。 不过用户体验的确不错。。
