### ISSUE TITLE
为什么双击翻译不了？

### ISSUE THREAD

**Issue by kingkong2013** [magic-FE/translate-man#9]
为什么我在页面上双击选择文字，翻译不了？我用debugger调试发现错误信息：

extensions::messaging:60 Uncaught (in promise) Error: Attempting to use a disconnected port object
    at PortImpl.postMessage (extensions::messaging:60:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:149:26)
    at responseCallback (extensions::messaging:166:16)
    at chrome-extension://akndolopllnakelkedkighpkjklgdfpk/static/js/background.js:76:14

另外，我是react新手，想请假一下如何调试页面上popup的翻译弹窗？我尝试设置"persistent": true，依然报上面的错误。

非常感谢！

**Comment by chen844033231** [comment]
@kingkong2013 哪个页面翻译报错的？贴上链接

**Comment by kingkong2013** [comment]
@chen844033231 好像任何页面翻译都有可能报错，我刚刚又试了一下。
譬如：
https://www.google.com/#q=Uncaught+(in+promise)+Error:+Attempting+to+use+a+disconnected+port+object
双击英文翻译成中文。

**Comment by chen844033231** [comment]
@kingkong2013 重现不了你要不试试卸载后重现装最新的 如果还有问题，反馈下 谢谢

**Comment by kingkong2013** [comment]
@chen844033231 
这个问题其实很好重现的，我的系统是英文环境，我把翻译目标语言选为日语。这个时候我双击选择英文，不能翻译。我提了一个PR，改了改。
我想提一个建议，如果修改了翻译目标语言，浏览器好像需要重启才能起作用，建议给用户一个提示。

**Comment by chen844033231** [comment]
@kingkong2013 目前页面中翻译采用是设置中的*主语言*，如果你是英文系统，所以默认你主语言是英文，也就是你能看懂全部英文，需要翻译请设置*主语言为中文*

**Comment by kingkong2013** [comment]
@chen844033231 我明白了，不过主语言这个设置比较迷惑人，一般我会去改Translate to，不会去改Translate from？
